export const OfferDefault = {
  COUNT: 60,
  DISCUSSED_COUNT: 5,
  NEW_COUNT: 5,
  RATING_VALUE: 5,
  COMMENTS_COUNT: 0,
  PHOTOS_COUNT: 6,
} as const;

export const OfferConst = {
  MIN_TITLE_LENGTH: 10,
  MAX_TITLE_LENGTH: 100,
  MIN_DESCRIPTION_LENGTH: 20,
  MAX_DESCRIPTION_LENGTH: 1024,
  MIN_ROOM_COUNT: 1,
  MAX_ROOM_COUNT: 8,
  MIN_GUEST_COUNT: 1,
  MAX_GUEST_COUNT: 10,
  MIN_PRICE: 100,
  MAX_PRICE: 100000,
} as const;
